# Generated by Django 2.2.2 on 2019-06-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('species', models.CharField(max_length=255, null=True)),
                ('character_type', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('origin', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(max_length=255)),
                ('location_resident', models.CharField(max_length=255)),
                ('type_resident', models.CharField(max_length=255)),
                ('type_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location_type', models.CharField(max_length=255, null=True)),
                ('dimension', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created', models.CharField(max_length=255, null=True)),
                ('residents', models.ManyToManyField(related_name='location_resident', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True)),
                ('Character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_characters', to='app.Character')),
                ('Location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_location', to='app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('air_date', models.CharField(max_length=255, null=True)),
                ('episode', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created', models.CharField(max_length=255, null=True)),
                ('characters', models.ManyToManyField(related_name='episode_character', to='app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='episode',
            field=models.ManyToManyField(related_name='character_episode', to='app.Episode'),
        ),
    ]
